version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: GOAPP
    ports:
      - 9090:9090
    depends_on:
      mysql:
        condition: service_healthy

    volumes:
      - ./config.json:/app/config.json
  
  mysql:
    image: mysql:5.7
    container_name: my-sql-server
    command: mysqld --user=root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10